config/routes.rb
Rails.application.routes.draw do
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/pagination.rb
module Pagination
  extend ActiveSupport::Concern
  attr_reader :collection

  def paginate(response, params: {})
    @collection = response["data"]
    params = params.merge(count: response["total"], total_pages: response["total_pages"])
    [
      ViewModel::Pagination.new(params),
      @collection
    ]
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show ]
  before_action :validate_params, only: [:index]
  include Pagination
  PER_PAGE = 5

  # GET /app_services
  def index
    # the reqres.in api does not support filter parameter. Therefore we filter after getting all employees
    if(params[:email].present?)
      response = AppServices::EmployeeService.new.get_all_employees
      @pagination, @employees = paginate(response, params: page_params)
      @employees = @employees.select {|employee| employee["email"].include?(params[:email])}
    else
      response = AppServices::EmployeeService.new.get_employees(page_params)
      @pagination, @employees = paginate(response, params: page_params)
    end
  end

  # GET /app_services/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = AppServices::EmployeeService.new.get_employee(params[:id])
    end

    def page_params
      { page: params[:page] || 1, per_page: params[:per_page] || PER_PAGE, email: params[:email] }
    end

    def validate_params
      param! :page, Integer, default: 1
      param! :per_page, Integer, default: PER_PAGE
      param! :email, String, required: false, format: URI::MailTo::EMAIL_REGEXP
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<table>
  <% if employees.empty? %>
    <p>There is no record</p>
  <% else %>
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Action</th>
    </tr>
  <% end %>

  <% employees.each do |employee| %>
    <tr>
      <td><%= employee["id"] %></td>
      <td><%= employee["email"] %></td>
      <td><%= employee["first_name"] %></td>
      <td><%= employee["last_name"] %></td>
      <td><%= link_to "Details", employee_path(employee["id"]) %></td>
    </tr>
  <% end %>

</table>

app/views/employees/_pagination.html.erb
<div>
  <% if  pagination.previous_page? %>
    <%= link_to 'First', employees_path(page: 1, per_page: params[:per_page]) %>
    <%= link_to '< Previous', employees_path(page: pagination.previous_page, per_page: params[:per_page]) %>
  <% else %>
    <span>First</span>
    <span>&#60; Previous</span>
  <% end %>
  <span><%= "Page #{pagination.page} of #{pagination.total_pages}" %></span>
  <% if pagination.next_page? %>
    <%= link_to 'Next >', employees_path(page: pagination.next_page, per_page: params[:per_page]) %>
    <%= link_to 'Last', employees_path(page: pagination.total_pages, per_page: params[:per_page]) %>
  <% else %>
    <span>Next &#62;</span>
    <span>Last </span>
  <% end %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>

<div id="employees">

  <%= form_tag employees_path, :method => "get" do %>
    <b>Email: </b>
    <%= email_field_tag :email, params[:email], :required => true %>
    <%= submit_tag "Search" %>
  <% end %>

  <%= render partial: 'employee', locals: { employees: @employees } %>
</div>

<% if params[:email].present? %>
  <%= link_to "Back to list", employees_path %>
<% end %>

<%= render partial: 'pagination', locals: { pagination: @pagination } %>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<h2>Employee Details</h2>
<p><%= image_tag(@employee["avatar"]) %> </p>
<p><b>Id: </b><%= @employee["id"] %></p>
<p><b>Email: </b><%= @employee["email"] %></p>
<p><b>First Name: </b><%= @employee["first_name"] %></p>
<p><b>Last Name: </b><%= @employee["last_name"] %></p>
<div>
  <%#= link_to "Edit this employee", edit_employee_path(@employee) %>
  <%= link_to "Back to employee list", employees_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>